### PR TITLE
added button

### PR DESCRIPTION
**Pull request by shiningshani**
## Have you read the Contribution Guidelines? If not, check [README.md](https://github.com/Design-and-Code/css-buttons#some-rules-to-contribute) file first.

Yes

## Description

I have added a hover button.

## Checklist

- [X] I've read the contribution guidelines.
- [X] I've checked the issue list before deciding what to submit.

> mark `[X]` to make it checked.

## Related Issues

Fixes Issue #23

### CODE REVIEW

**Comment by shiningshani** [comment]
I have resolved the conflicts. Make sure to merge the pull request.

**Comment by Rajkumar-justcoder** [comment]
> I have resolved the conflicts. Please merge the pull request.

hey there,
image
button text is not visible on hover so can u pls fix this and also 
give your css class name as yourname-button-1 aka shiningshani-button-1

**Comment by shiningshani** [comment]
> > I have resolved the conflicts. Please merge the pull request.
> 
> hey there, image button text is not visible on hover so can u pls fix this and also give your css class name as yourname-button-1 aka shiningshani-button-1

image
its fine now😍

**Comment by Rajkumar-justcoder** [comment]
but u have not changes your class names
nvm i will merge it

**Comment by Rajkumar-justcoder** [comment]
LGTM!!

**Comment by shiningshani** [comment]
The way you are maintaining your repos requires great deal of effort. I'm impressed by your hard work and patience (especially the way you helped me). 
Thanks for giving your valuable time to a beginner me.

**Comment by Rajkumar-justcoder** [comment]
Thanks for appreciation 🤗.

And no problem ( its our duty to answers to the ques ) 
nvm forgot that and enjoy ✌️

**Pull request merged**
