### PR TITLE
Button added: Gradient Hover

### PR DESCRIPTION
**Pull request by HarshJa1n**
## Have you read the Contribution Guidelines? If not, check [README.md](https://github.com/Design-and-Code/css-buttons#some-rules-to-contribute) file first.

Yes

## Description

A Button built using CSS animation and gradient properties.

## Checklist

- [X] I've read the contribution guidelines.
- [X] I've checked the issue list before deciding what to submit.

## Related Issues

Fixes Issue #67

### CODE REVIEW

**Comment by Rajkumar-justcoder** [comment]
Hey may i know how many times your pr is closed ?

**Comment by Rajkumar-justcoder** [comment]
told that yourname-button-23 or yourname-button-eyes-23, yourname-button-mouth23
means all names of class inside button container should be like that 

nvm

**Comment by Rajkumar-justcoder** [comment]
nvm i have merged if after fix conflict

**Comment by Rajkumar-justcoder** [comment]
LGTM!!!  I like your second button

**Comment by HarshJa1n** [comment]
OMG! Thankyou!! and I am sorry for the naming error, I didnt get that right.

**Comment by HarshJa1n** [comment]
I wanted to do separate PRs for the two buttons,  but I messed up and committed on the same branch, tried resolving it but couldn't.

**Comment by Rajkumar-justcoder** [comment]
> I wanted to do separate PRs for the two buttons, but I messed up and committed on the same branch, tried resolving it but couldn't.

no problem i tell to two three time is then i know that u u are having some issue with this so solved this

**Comment by Rajkumar-justcoder** [comment]
> OMG! Thankyou!! and I am sorry for the naming error, I didnt get that right.

Any time bro + sry i cant tell u in specificy ( explainu nice ice way ) way

**Pull request merged**
