### PR TITLE
created new button

### PR DESCRIPTION
**Pull request by Cypher1002**
## Have you read the Contribution Guidelines? If not, check [README.md](https://github.com/Design-and-Code/css-buttons#some-rules-to-contribute) file first.
yes 

## Description
created a button with animations 
this is my second pull request 

## Checklist

- [x ] I've read the contribution guidelines.
- [ x] I've checked the issue list before deciding what to submit.

> mark `[X]` to make it checked.

## Related Issues

Fixes Issue #48 

please consider this contribution under hacktoberfest

### CODE REVIEW

**Comment by Cypher1002** [comment]
@Rajkumar-justcoder please review

**Comment by Rajkumar-justcoder** [comment]
image
your button is outside the main div idk how but it is

**Comment by Rajkumar-justcoder** [comment]
also while fixing 
pls add yourname-btn-1 in your first button  which is this 
image

**Comment by Rajkumar-justcoder** [comment]
> also while fixing pls add yourname-btn-1 in your first button which is this image

insted of yourname-btn

**Comment by Cypher1002** [comment]
Ok

**Pull request closed without merging**
