### PR TITLE
fix(grammar): Fixing quite a few errors

### PR DESCRIPTION
**Pull request by cameronball**
## Have you read the Contribution Guidelines? If not, check [README.md](https://github.com/Design-and-Code/css-buttons#some-rules-to-contribute) file first.

Yes

## Description

Fixed a few spelling/grammar errors in the README file.

## Checklist

- [X] I've read the contribution guidelines.
- [X] I've checked the issue list before deciding what to submit.

### CODE REVIEW

**Comment by Rajkumar-justcoder** [comment]
> If you decide to merge, please add “hacktoberfest-accepted” so it can count towards my Hacktoberfest 2022 progress :)

yeah sure will add that can u pls change requested changes

**Comment by cameronball** [comment]
> > If you decide to merge, please add “hacktoberfest-accepted” so it can count towards my Hacktoberfest 2022 progress :)
> 
> yeah sure will add that can u pls change requested changes

Not sure I quite follow, what is it exactly you’d like me to change?

**Comment by cameronball** [comment]
@Rajkumar-justcoder committed 😄

**Review by Rajkumar-justcoder — APPROVED** [review]

**Comment by Rajkumar-justcoder** [comment]
> @Rajkumar-justcoder committed smile

Merged :hugs:

**Comment by Rajkumar-justcoder** [comment]
LGTM!!

**Pull request merged**
