### PR TITLE
Added a new button with hover effect

### PR DESCRIPTION
**Pull request by radzhiv25**
## Have you read the Contribution Guidelines? If not, check [README.md](https://github.com/Design-and-Code/css-buttons#some-rules-to-contribute) file first.

Yes

## Description

Created a button with hover effect and some animation

## Checklist

- [ X] I've read the contribution guidelines.
- [ X] I've checked the issue list before deciding what to submit.

> mark `[X]` to make it checked.

## Related Issues
Just added some animation over hover

Fixes Issue # (write number after `#`)
#91

### CODE REVIEW

**Comment by radzhiv25** [comment]
How can i resolve the merge conflict

**Comment by Rajkumar-justcoder** [comment]
+ name convention of css classes does not match so kindly pls read readme.md insted of writing yes in pr template 

- yourname-button-index

**Comment by Rajkumar-justcoder** [comment]
also name of key frame also would be like 
image

- yourname(githubusername)-button-1-hue(keyframename)
(..) this are for reference

**Comment by Rajkumar-justcoder** [comment]
now main point to resolve conflict u need to keep update your branch with main branch

**Comment by Rajkumar-justcoder** [comment]
so i am closing this pr and u can open new pr with all changes

**Comment by radzhiv25** [comment]
> so i am closing this pr and u can open new pr with all changes

so new issue is to be created or what ??

**Pull request closed without merging**
