### PR TITLE
Added a button

### PR DESCRIPTION
**Pull request by mjmanas54**
## Have you read the Contribution Guidelines? If not, check [README.md](https://github.com/Design-and-Code/css-buttons#some-rules-to-contribute) file first.

Yes

## Description

I had read the guidlines

## Checklist

- [X] I've read the contribution guidelines.
- [X] I've checked the issue list before deciding what to submit.

> mark `[X]` to make it checked.

## Related Issues

Fixes Issue # (write number after `#`)

### CODE REVIEW

**Comment by mjmanas54** [comment]
I am not able to understand why my PR is conflicting, someone please help me.

**Comment by Rajkumar-justcoder** [comment]
> I am not able to understand why my PR is conflicting, someone please help me.

your pr is conflict cause of all other are adding button name as btn1 btn10 etc 
So u can just use poper name convention listed in readme.md which is 
yourname-button-index

**Comment by Rajkumar-justcoder** [comment]
> > I am not able to understand why my PR is conflicting, someone please help me.
> 
> your pr is conflict cause of all other are adding button name as btn1 btn10 etc So u can just use poper name convention listed in readme.md which is yourname-button-index

this is for css class name convention so change css class name in both file button.css and index.html

**Comment by Rajkumar-justcoder** [comment]
also remove type='buttom' from html code

**Pull request closed without merging**
