### PR TITLE
Added one more button

### PR DESCRIPTION
**Pull request by radzhiv25**
> **Note**
> - We strictly follow the Contribution Guideline and expect contributors to follow it as well. 
> - If a lot of conflicts/changes are requested in the PR, please open a new PR with the requested changes (either you or we can close the PR). 

## Have you read the Contribution Guidelines? If not, check [CONTRIBUTING.md](https://github.com/Design-and-Code/css-buttons/blob/main/CONTRIBUTING.md) file first.

Yes

## Description

Added button with effects

## Class Naming Convention for your button
- [X ] Does your html `button` element have class-name like this: `your_github_username-button-index` (example: `rajkumar-justcoder-button-1` ). 

## Checklist

- [X ] I've read the contribution guidelines.
- [X ] I've checked the issue list before deciding what to submit.

> mark `[X]` to make it checked.

## Related Issues

Fixes Issue #114 

## Screenshot
image

### CODE REVIEW

**Comment by radzhiv25** [comment]
@Rajkumar-justcoder please update

**Comment by Rajkumar-justcoder** [comment]
do u know how to fix merge conflict ?
and what about this 
image

**Comment by radzhiv25** [comment]
> do u know how to fix merge conflict ?
> 
> and what about this 
> 
> image
> 
> 

Sorry for the same will do it again

**Comment by radzhiv25** [comment]
> yeah + that not how u solve merge conflict 
> 
> u have to accept incoming changes 

Please update

**Pull request closed without merging**
