### PR TITLE
Added 3 unique buttons

### PR DESCRIPTION
**Pull request by AmitSahoo45**
I have added 3 unique buttons using HTML & CSS.

### CODE REVIEW

**Comment by Rajkumar-justcoder** [comment]
Hey Can u pls solve Conflict

**Comment by AmitSahoo45** [comment]
I don't really understand what's really the conflict is when I have just added the code to the index.html and button.css and haven't even changed anything else. If you take 2 mins and look at the code, then there is literally no change to the previous code.

It just shows whatever code I have added is just a conflict.

**Comment by AmitSahoo45** [comment]
Can you check now???? It is showing all checks have passed and "This branch has no conflicts with the base branch"

**Comment by Rajkumar-justcoder** [comment]
> Can you check now???? It is showing all checks have passed and "This branch has no conflicts with the base branch"

Yup all things are fixed

**Comment by Rajkumar-justcoder** [comment]
LGTM!!

**Pull request merged**
