### PR TITLE
Added a new button with hover effect

### PR DESCRIPTION
**Pull request by akashyap25**

### CODE REVIEW

**Comment by Rajkumar-justcoder** [comment]
Pls read readme.md file in repo and check how to do give names to classes 
Button-123..
Or
Button-your_name
As redefine will over right default buttons css

**Comment by akashyap25** [comment]
> Pls read readme.md file in repo and check how to do give names to classes Button-123.. Or Button-your_name As redefine will over right default buttons css

Named it button - 9

**Comment by Rajkumar-justcoder** [comment]
Hey There is massive conflict so pls resolve it +
after telling also in css u have not changed to with your respective name according to class
by giving that same name it overwrite other button + i have review in code also

**Comment by akashyap25** [comment]
> Hey There is massive conflict so pls resolve it + after telling also in css u have not changed to with your respective name according to class by giving that same name it overwrite other button + i have review in code also

Sorry for that, I have  changed the name in both can you please review it.

**Comment by Rajkumar-justcoder** [comment]
LGTM!!!

**Pull request merged**
