### PR TITLE
added a animated css button

### PR DESCRIPTION
**Pull request by gauravsharmatheofficial**
> **Note**
> - We strictly follow the Contribution Guideline and expect contributors to follow it as well. 
> - If a lot of conflicts/changes are requested in the PR, please open a new PR with the requested changes (either you or we can close the PR). 

## Have you read the Contribution Guidelines? If not, check [CONTRIBUTING.md](https://github.com/Design-and-Code/css-buttons/blob/main/CONTRIBUTING.md) file first.

Yes

## Description

Added a animated CSS button

## Class Naming Convention for your button
- [X] Does your html `button` element have class-name like this: `your_github_username-button-index` (example: `rajkumar-justcoder-button-1` ). 

## Checklist

- [X] I've read the contribution guidelines.
- [X] I've checked the issue list before deciding what to submit.

> mark `[X]` to make it checked.

## Related Issues

Fixes Issue #114 

## Screenshot
image

### CODE REVIEW

**Comment by gauravsharmatheofficial** [comment]
ok

**Comment by Rajkumar-justcoder** [comment]
I guess u didn't readed contribution guide

**Comment by Rajkumar-justcoder** [comment]
Go there and see demo code and see how i have given class names

**Comment by Rajkumar-justcoder** [comment]
+ if u know css then if class name or tag is repeat again with diff property then it overwrite
So u know what should be done

**Pull request merged**
